/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI_forms;

import com.hospital.hospitalmgmnt.Doctor;
import com.hospital.hospitalmgmnt.DoctorDirectory;
import com.hospital.hospitalmgmnt.FormsPanels.CreatePerson;
import com.hospital.hospitalmgmnt.Hospital;
import com.hospital.hospitalmgmnt.HospitalDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Divyesh Rajput
 */
public class SearchHospitalPanel extends javax.swing.JPanel {

    /**
     * Creates new form SearchHospitalPanel
     */
    HospitalDirectory hospital;
    DoctorDirectory doctor;
    Doctor dr;
    public SearchHospitalPanel(DoctorDirectory doctor, HospitalDirectory hospital) {
        initComponents();
        this.hospital = hospital;
        this.doctor= doctor;
        populateTable();  
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        txtCommunity = new javax.swing.JTextField();
        jSearchHospital = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDoctor = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblHospital = new javax.swing.JTable();
        jViewDoctors = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(700, 600));

        jLabel1.setText("City");

        jLabel2.setText("Community");

        jSearchHospital.setText("Search");
        jSearchHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSearchHospitalActionPerformed(evt);
            }
        });

        tblDoctor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "DoctorID", "Doctor Name", "Department", "Contact No. "
            }
        ));
        jScrollPane1.setViewportView(tblDoctor);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("(Please click a record to view doctors in that hospital)");

        tblHospital.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "HospitalID", "HospitalName", "Street Address", "Community", "City"
            }
        ));
        jScrollPane2.setViewportView(tblHospital);

        jViewDoctors.setText("View Doctors");
        jViewDoctors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jViewDoctorsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 9, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCity, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                                    .addComponent(txtCommunity))
                                .addGap(18, 18, 18)
                                .addComponent(jSearchHospital, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(283, 283, 283)
                        .addComponent(jViewDoctors, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jSearchHospital, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jViewDoctors)
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jSearchHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSearchHospitalActionPerformed
        // TODO add your handling code here:
      String citySearch =  txtCity.getText();
      String communitySearch = txtCommunity.getText();
      
      searchHospitals(citySearch, communitySearch);

    }//GEN-LAST:event_jSearchHospitalActionPerformed

    private void jViewDoctorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jViewDoctorsActionPerformed
        // TODO add your handling code here:

        int selectedRowIndex = tblHospital.getSelectedRow();

        if (selectedRowIndex<0){
            JOptionPane.showMessageDialog(this, "Please select a record to view");
        }

        DefaultTableModel model = (DefaultTableModel) tblDoctor.getModel();
        Hospital hos;
        int flag1 = -1;
        String hName = (String) tblHospital.getValueAt(selectedRowIndex , 1);
        model.setRowCount(0);
        for (Doctor dr : doctor.getdoctorList()){
           if(dr.getDrHospital().equals(hName)){
                    Object[] row = new Object[5];
                    row[0] = dr;
                    row[1]= dr.getdrName();
                    row[2]= dr.getDrSpeciality();
                    row[3]= dr.getDrContact();
                    model.addRow(row);
                    flag1 = 1;
                    
           }
           else
               flag1 = -1;
           
        }
        if (flag1 < 0)
            JOptionPane.showMessageDialog(this, "Doctor Not Found!!!");
        
    }//GEN-LAST:event_jViewDoctorsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jSearchHospital;
    private javax.swing.JButton jViewDoctors;
    private javax.swing.JTable tblDoctor;
    private javax.swing.JTable tblHospital;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtCommunity;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
       // throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    DefaultTableModel model = (DefaultTableModel) tblHospital.getModel();
        model.setRowCount(0);
        for (Hospital hp : hospital.getHospital()){
            Object[] row = new Object[5];
            row[0] = hp;
            row[1]= hp.getHospitalName();
            row[2]= hp.getStreetAddress();
            row[3]=hp.getCommunity_name();
            row[4]=hp.getCityName();
            
            model.addRow(row);
        }
        
    }


    private void searchHospitals(String citySearch, String communitySearch) {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            DefaultTableModel tblmodel = (DefaultTableModel) tblHospital.getModel();
        tblmodel.setRowCount(0);
        int flag = -1;
        
        for (Hospital hp : hospital.getHospital()){
            Object[] row = new Object[5];
            if(!"".equals(citySearch) && !"".equals(communitySearch) ){
                if (hp.getCityName().equals(citySearch) && hp.getCommunity_name().equals(communitySearch)){
                    row[0] = hp;
            row[1]= hp.getHospitalName();
            row[2]= hp.getStreetAddress();
            row[3]=hp.getCommunity_name();
            row[4]=hp.getCityName();
                    tblmodel.addRow(row);
                    flag = 1;
                    
                }
            }
            else if (!"".equals (citySearch)){
                if (hp.getCityName().equals(citySearch)){
                    row[0] = hp;
            row[1]= hp.getHospitalName();
            row[2]= hp.getStreetAddress();
            row[3]=hp.getCommunity_name();
            row[4]=hp.getCityName();
                    tblmodel.addRow(row);
                    
                    flag = 1;
                }
            } else if (!"".equals (communitySearch)){
                if (hp.getCommunity_name().equals(communitySearch)){
                    row[0] = hp;
                    row[1]= hp.getHospitalName();
                    row[2]= hp.getStreetAddress();
                    row[3]=hp.getCommunity_name();
                    row[4]=hp.getCityName();
                    
                    tblmodel.addRow(row);
                    flag = 1; 
                }    
        } else {
                flag = -1;
            }
            
    }
    if (flag <0){
                JOptionPane.showMessageDialog(this, "Hospital Not Found!!!");
            }
    }
}
